title: SATRIO BAYU TIRTO LAKSONO
logo: /img/foto  shoot circle cv .png
Adescritption: I am a passionate in the field of data analysis. I have committed to developing myself in this area and have attended a number of courses and training related to data analysis.
show_downloads: true
theme: jekyll-theme-minimal
