title: SATRIO BAYU TIRTO LAKSONO
logo: /img/foto cv - Copy.jpg
descritption: I am a passionate newbie in the field of data analysis. I have committed myself to develop myself in this regard and have attended a number of courses and trainings related to data analysis
show_download: true
theme: jekyll-theme-minimal
